In [7]:
# Importing Libraries

import csv
import pandas as pd
import pymysql
from sqlalchemy import create_engine

In [9]:
# Setting up some basic logging
import logging 
  
#Config logger
logging.basicConfig(filename="output.log", 
                    format='%(asctime)s %(message)s', 
                    filemode='w') 
  
#Creating an object 
logger=logging.getLogger() 
  
#Setting the threshold of logger to DEBUG 
logger.setLevel(logging.INFO) 
  
#Test messages 
logger.info("Starting the process")

In [11]:
# Creating the database connection/engine to root (localhost on the box)
engine = create_engine('mysql+mysqlconnector://root@localhost/etl_sandbox')
logger.info("Database connection made")

In [12]:
# There are two methods we can use to load this into the database
# 1) Use Pandas read_csv method and then just do a to_sql() call
# 2) Open the CSV File, auto-generate the table structure, then insert the data into it
# We will go through both methods here

###########################################################
#
#         Method 1 (Pandas Read CSV Functionality)
#
###########################################################

# Loading the data
df = pd.read_csv('appstore_games.csv', sep=",")

# Listing top 5 rows to make sure it's loaded appropriately
df.head()

# Writing it to the MySQL instance
# Using chunksize as to not failover the buffer limit
db_table_name = "app_games"
df.to_sql(db_table_name, con=engine, if_exists="replace", chunksize=1000)

# Logging
logger.info("Read the CSV into the Database")

In [13]:
# Confirm the table is loaded correctly
sql_df = pd.read_sql_query("SELECT * FROM etl_sandbox.app_games", con=engine)
sql_df.head()

,index,URL,ID,Name,Subtitle,Icon URL,Average User Rating,User Rating Count,Price,In-app Purchases,Description,Developer,Age Rating,Languages,Size,Primary Genre,Genres,Original Release Date,Current Version Release Date
0,0,https://apps.apple.com/us/app/sudoku/id284921427,284921427,Sudoku,None,https://is2-ssl.mzstatic.com/image/thumb/Purpl...,4.0,3553.0,2.99,None,"Join over 21,000,000 of our fans and download ...",Mighty Mighty Good Games,4+,"DA, NL, EN, FI, FR, DE, IT, JA, KO, NB, PL, PT...",15853568.0,Games,"Games, Strategy, Puzzle",11/07/2008,30/05/2017
1,1,https://apps.apple.com/us/app/reversi/id284926400,284926400,Reversi,None,https://is4-ssl.mzstatic.com/image/thumb/Purpl...,3.5,284.0,1.99,None,"The classic game of Reversi, also known as Oth...",Kiss The Machine,4+,EN,12328960.0,Games,"Games, Strategy, Board",11/07/2008,17/05/2018
2,2,https://apps.apple.com/us/app/morocco/id284946595,284946595,Morocco,None,https://is5-ssl.mzstatic.com/image/thumb/Purpl...,3.0,8376.0,0.00,None,Play the classic strategy game Othello (also k...,Bayou Games,4+,EN,674816.0,Games,"Games, Board, Strategy",11/07/2008,5/09/2017
3,3,https://apps.apple.com/us/app/sudoku-free/id28...,285755462,Sudoku (Free),None,https://is3-ssl.mzstatic.com/image/thumb/Purpl...,3.5,190394.0,0.00,None,"Top 100 free app for over a year.\nRated ""Best...",Mighty Mighty Good Games,4+,"DA, NL, EN, FI, FR, DE, IT, JA, KO, NB, PL, PT...",21552128.0,Games,"Games, Strategy, Puzzle",23/07/2008,30/05/2017
4,4,https://apps.apple.com/us/app/senet-deluxe/id2...,285831220,Senet Deluxe,None,https://is1-ssl.mzstatic.com/image/thumb/Purpl...,3.5,28.0,2.99,None,"""Senet Deluxe - The Ancient Game of Life and A...",RoGame Software,4+,"DA, NL, EN, FR, DE, EL, IT, JA, KO, NO, PT, RU...",34689024.0,Games,"Games, Strategy, Board, Education",18/07/2008,22/07/2018

In [15]:
###########################################################
#
#             Method 2 (Auto-generate SQL)
#
#    This method is slightly more unreliable, especially
#    if your data in the first row has null or blank values.
#    This makes it difficult to read what data types
#    the fields should be in MySQL
#
###########################################################

import csv
with open('appstore_games.csv', newline='') as f:
    reader = csv.reader(f)
    row1 = next(reader)
    row2 = next(reader)
    
create_l1 = "CREATE TABLE IF NOT EXISTS appstore_games("
create_l2 = []
create_l3 = ")"

# Writing column name and data type to a schema
for i in range(0,len(row1)):
    # Grab data type - for now we will just assume all varchar
    # Another way to do this is to check the second row
    # and for each row of data, grab the type() and map it to the {column} {datatype}, 
    
    datatype = "VARCHAR(500)"
    data = row1[i].lower().replace("-","_").replace(" ","_")
    create_l2.append(data + " " + datatype)

# Joining them into a single string
create_l2 = ','.join(create_l2)

# Combining the strings to create a single SQL statement
query = create_l1 + create_l2 + create_l3
print(query)

# Running the query
import pymysql.cursors

# Connect to the database
connection = pymysql.connect(host='localhost',
                             user='root',
                             password='',
                             db='etl_sandbox',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)

try:
    with connection.cursor() as cursor:        
        # Execute the query
        cursor.execute(query)
        
    connection.commit()
    logger.info("Successfully created blank data set using auto-generated SQL.")
finally:
    connection.close()

CREATE TABLE IF NOT EXISTS appstore_games(url VARCHAR(500),id VARCHAR(500),name VARCHAR(500),subtitle VARCHAR(500),icon_url VARCHAR(500),average_user_rating VARCHAR(500),user_rating_count VARCHAR(500),price VARCHAR(500),in_app_purchases VARCHAR(500),description VARCHAR(500),developer VARCHAR(500),age_rating VARCHAR(500),languages VARCHAR(500),size VARCHAR(500),primary_genre VARCHAR(500),genres VARCHAR(500),original_release_date VARCHAR(500),current_version_release_date VARCHAR(500))

C:\Users\cosykes\AppData\Local\Continuum\anaconda3\lib\site-packages\pymysql\cursors.py:329: Warning: (1050, "Table 'appstore_games' already exists")
  self._do_get_result()